### ISSUE TITLE
"Зворотній звязок" - не работает

### ISSUE THREAD

**Issue by valentinsiryk** [Onix-Systems/rename.kr.ua#9]
Кнопка "Зворотній звязок" не работает.

Refused to display 'https://onixsystems.freshdesk.com/support/login' in a frame because it set 'X-Frame-Options' to 'deny'

**Comment by xainse** [comment]
@valentinsiryk замінили посилання на фрешдеск посилання на створення issue на github

**Comment by valentinsiryk** [comment]
> @valentinsiryk замінили посилання на фрешдеск посилання на створення issue на github

Добре, дякую)
